name: quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Style
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8

  # Info
  device_info_plus: ^11.3.0
  uuid: ^4.5.1

  # Localization
  flutter_localizations:
    sdk: flutter
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.2

  # Api
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Storage
  shared_preferences: ^2.5.2
  drift: ^2.13.0
  drift_flutter: ^0.2.4
  path: ^1.9.0
  path_provider: ^2.1.5

  # State
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

  # DI
  injectable_generator: ^2.6.2

  # Storage
  drift_dev: ^2.13.0

flutter:
  uses-material-design: true
