name: quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  slang: ^4.5.0
  slang_flutter: ^4.5.0

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_remote_config: ^5.4.2
  cloud_firestore: ^5.6.5

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Storage
  shared_preferences: ^2.5.2

  # State
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.13

  # DI
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
